import {
  GatewayConfig,
  GatewayReviewRequest,
  GatewayReviewResponse,
  REVIEW_SEVERITIES,
  ReviewFinding,
  ReviewSeverity
} from '@code-reviewer/shared-types';

const MAX_DIFF_CHARS = 120000;
const REQUEST_TIMEOUT_MS = 120000;
const MAX_TITLE_CHARS = 80;
const MAX_SUMMARY_CHARS = 180;

function normalizeBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.trim();
  if (!trimmed) {
    throw new Error('ai_base_url is required for gateway mode.');
  }

  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new Error(`Invalid ai_base_url: "${baseUrl}". Provide a valid http(s) URL.`);
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error(`Invalid ai_base_url protocol: "${parsed.protocol}". Use http or https.`);
  }

  const normalizedPath = parsed.pathname.endsWith('/') ? parsed.pathname.slice(0, -1) : parsed.pathname;
  parsed.pathname = normalizedPath;
  return parsed.toString();
}

function truncateDiff(diff: string): { text: string; truncated: boolean } {
  if (diff.length <= MAX_DIFF_CHARS) {
    return { text: diff, truncated: false };
  }

  return {
    text: `${diff.slice(0, MAX_DIFF_CHARS)}\n\n[diff truncated for token safety]`,
    truncated: true
  };
}

function normalizeSeverity(value: unknown): ReviewSeverity | null {
  if (typeof value !== 'string') {
    return null;
  }

  const severity = value.trim().toLowerCase();
  return REVIEW_SEVERITIES.includes(severity as ReviewSeverity) ? (severity as ReviewSeverity) : null;
}

function compactWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function truncateText(value: string, maxChars: number): string {
  if (value.length <= maxChars) {
    return value;
  }

  const clipped = value.slice(0, maxChars - 3).trimEnd();
  const lastSpace = clipped.lastIndexOf(' ');
  const safeCutoff = Math.floor(maxChars * 0.6);
  const compact = lastSpace >= safeCutoff ? clipped.slice(0, lastSpace) : clipped;
  return `${compact}...`;
}

const MAX_SUGGESTION_CHARS = 500;

function coerceFinding(raw: unknown): ReviewFinding | null {
  if (!raw || typeof raw !== 'object') {
    return null;
  }

  const item = raw as Record<string, unknown>;
  const severity = normalizeSeverity(item.severity);
  const title =
    typeof item.title === 'string'
      ? truncateText(compactWhitespace(item.title), MAX_TITLE_CHARS)
      : '';
  const summary =
    typeof item.summary === 'string'
      ? truncateText(compactWhitespace(item.summary), MAX_SUMMARY_CHARS)
      : '';

  if (!severity || !title || !summary) {
    return null;
  }

  const filePath = typeof item.filePath === 'string'
    ? item.filePath.trim()
    : typeof item.file === 'string'
      ? item.file.trim()
      : undefined;

  const line =
    typeof item.line === 'number' && Number.isInteger(item.line) && item.line > 0 ? item.line : undefined;

  const confidence =
    typeof item.confidence === 'number' && Number.isFinite(item.confidence)
      ? Math.max(0, Math.min(1, item.confidence))
      : undefined;

  const suggestion =
    typeof item.suggestion === 'string' && item.suggestion.trim()
      ? truncateText(item.suggestion.trim(), MAX_SUGGESTION_CHARS)
      : undefined;

  return {
    severity,
    title,
    summary,
    suggestion,
    filePath: filePath || undefined,
    line,
    confidence
  };
}

function buildPrompt(request: GatewayReviewRequest, truncated: boolean): string {
  const fileList = request.files.map(file => `- ${file.path} (${file.status ?? 'modified'})`).join('\n');
  const isAgent = request.context?.agent?.isAgentAuthored === true;

  const jsonShape = isAgent
    ? '{"findings":[{"severity":"low|medium|high|critical","title":"...","summary":"...","suggestion":"...","filePath":"...","line":123,"confidence":0.0}]}'
    : '{"findings":[{"severity":"low|medium|high|critical","title":"...","summary":"...","filePath":"...","line":123,"confidence":0.0}]}';

  const rules = [
    '- Findings must be concrete and evidence-based.',
    '- Report only issues directly grounded in changed lines from this diff.',
    '- If you cannot anchor a finding to a specific changed line, omit it.',
    '- Do not suggest cosmetic renames or data-model renames/migrations unless diff shows a concrete bug.',
    '- Use higher severity only for significant risk.',
    '- Use filePath and line when possible.',
    '- Keep title concise (max 12 words).',
    '- Keep summary concise (max 28 words).',
    '- Avoid filler text, disclaimers, and repetition.',
    '- confidence must be between 0 and 1.',
  ];

  if (isAgent) {
    rules.push(
      '- This code was generated by an AI coding agent. Agents systematically over-produce code. Apply these rules:',
      '',
      '- BLOAT DETECTION (high priority):',
      '  - Flag helper functions, utilities, or abstractions that are used only once. Inline them.',
      '  - Flag wrapper functions that just call another function with the same args.',
      '  - Flag error handling for conditions that cannot occur (e.g., catching errors from infallible operations).',
      '  - Flag config objects, options parameters, or feature flags when only one value is ever used.',
      '  - Flag type definitions or interfaces that are used in exactly one place. Use inline types.',
      '  - Flag excessive comments that restate what the code does. Code should be self-documenting.',
      '  - Flag added files that could be a few lines in an existing file instead.',
      '  - If 3 lines of direct code would work, flag the 15-line abstraction.',
      '',
      '- AGENT ARTIFACTS:',
      '  - Flag imports that are added but never used in the diff.',
      '  - Flag variables declared but never read.',
      '  - Flag TODO/FIXME comments that the agent left for itself.',
      '  - Flag console.log/debug statements left in production code.',
      '',
      '- CORRECTNESS:',
      '  - Flag changed function signatures where callers may not have been updated.',
      '  - Flag hardcoded values (URLs, secrets, magic numbers) that should be config/env.',
      '  - Flag disabled or weakened validation, auth checks, or safety guards.',
      '',
      '- For each finding, provide a "suggestion" field with the simpler/corrected code.',
      '- Prefer fewer, higher-quality findings over many low-value ones.',
    );
  }

  if (truncated) {
    rules.push('- Note: diff content was truncated for token safety.');
  }

  // Build custom rules section
  const customRules = request.context?.customRules?.filter(r => r.trim().length > 0) ?? [];
  const customRulesSection = customRules.length > 0
    ? [
        '',
        'Project-specific rules (enforced by the user -- treat as high priority):',
        ...customRules.map(r => `- ${r}`),
      ]
    : [];

  return [
    'Review this pull request diff and return ONLY JSON with this shape:',
    jsonShape,
    'Rules:',
    ...rules,
    ...customRulesSection,
    '',
    `Review tone: ${request.context?.reviewTone ?? 'balanced'}`,
    `Repository: ${request.context?.repoFullName ?? 'unknown'}`,
    `PR Number: ${request.context?.prNumber ?? 'unknown'}`,
    '',
    'Changed files:',
    fileList || '- none',
    '',
    'Diff:',
    request.diff
  ].filter(Boolean).join('\n');
}

export async function reviewDiffWithOpenAICompatibleGateway(
  config: GatewayConfig,
  request: GatewayReviewRequest
): Promise<GatewayReviewResponse> {
  const baseUrl = normalizeBaseUrl(config.baseUrl);
  const endpoint = `${baseUrl}/chat/completions`;

  const diffResult = truncateDiff(request.diff);
  const prompt = buildPrompt({ ...request, diff: diffResult.text }, diffResult.truncated);

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let response: Response;
  try {
    response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${config.apiKey}`
      },
      body: JSON.stringify({
        model: config.model,
        temperature: 0.1,
        response_format: { type: 'json_object' },
        messages: [
          {
            role: 'system',
            content:
              'You are a senior code reviewer who values simplicity. Less code is better code. Flag anything that adds complexity without clear necessity. Return strict JSON only in the requested schema. Every finding must point to a specific line in the diff. No speculation, no filler.'
          },
          {
            role: 'user',
            content: prompt
          }
        ]
      }),
      signal: controller.signal
    });
  } catch (error) {
    if (error instanceof Error && error.name === 'AbortError') {
      throw new Error(`Gateway request timed out after ${Math.floor(REQUEST_TIMEOUT_MS / 1000)} seconds.`);
    }

    throw new Error(`Gateway request failed: ${String(error)}`);
  } finally {
    clearTimeout(timeoutId);
  }

  const rawResponse = await response.text();

  if (!response.ok) {
    throw new Error(
      `Gateway request failed with status ${response.status}. Response: ${rawResponse.slice(0, 1000)}`
    );
  }

  let outer: unknown;
  try {
    outer = JSON.parse(rawResponse);
  } catch {
    throw new Error('Gateway response was not valid JSON.');
  }

  const messageContent =
    outer &&
    typeof outer === 'object' &&
    Array.isArray((outer as { choices?: unknown[] }).choices) &&
    (outer as { choices: Array<{ message?: { content?: unknown } }> }).choices.length > 0
      ? (outer as { choices: Array<{ message?: { content?: unknown } }> }).choices[0]?.message?.content
      : undefined;

  if (typeof messageContent !== 'string' || !messageContent.trim()) {
    throw new Error('Gateway response did not include choices[0].message.content.');
  }

  let inner: unknown;
  try {
    inner = JSON.parse(messageContent);
  } catch {
    throw new Error('Gateway content field was not valid JSON.');
  }

  const rawFindings =
    inner && typeof inner === 'object' && Array.isArray((inner as { findings?: unknown }).findings)
      ? (inner as { findings: unknown[] }).findings
      : [];

  const findings = rawFindings.map(coerceFinding).filter((finding): finding is ReviewFinding => finding !== null);

  return {
    findings,
    rawResponse
  };
}

// Exported for testing only
export const _test = { coerceFinding, truncateDiff, buildPrompt, normalizeSeverity, normalizeBaseUrl };
