import {
  GatewayReviewRequest,
  GatewayReviewResponse,
  ReviewFinding,
  ReviewSeverity,
  REVIEW_SEVERITIES,
} from '@code-reviewer/shared-types';

const MAX_DIFF_CHARS = 120_000;
const MAX_TITLE_CHARS = 80;
const MAX_SUMMARY_CHARS = 180;
const MAX_SUGGESTION_CHARS = 500;

export function truncateDiff(diff: string): { text: string; truncated: boolean } {
  if (diff.length <= MAX_DIFF_CHARS) {
    return { text: diff, truncated: false };
  }
  return {
    text: `${diff.slice(0, MAX_DIFF_CHARS)}\n\n[diff truncated for token safety]`,
    truncated: true,
  };
}

function normalizeSeverity(value: unknown): ReviewSeverity | null {
  if (typeof value !== 'string') return null;
  const severity = value.trim().toLowerCase();
  return REVIEW_SEVERITIES.includes(severity as ReviewSeverity)
    ? (severity as ReviewSeverity)
    : null;
}

function compactWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function truncateText(value: string, maxChars: number): string {
  if (value.length <= maxChars) return value;
  const clipped = value.slice(0, maxChars - 3).trimEnd();
  const lastSpace = clipped.lastIndexOf(' ');
  const safeCutoff = Math.floor(maxChars * 0.6);
  const compact =
    lastSpace >= safeCutoff ? clipped.slice(0, lastSpace) : clipped;
  return `${compact}...`;
}

/** Coerce a raw LLM finding object into a validated ReviewFinding, or null if invalid */
export function coerceFinding(raw: unknown): ReviewFinding | null {
  if (!raw || typeof raw !== 'object') return null;

  const item = raw as Record<string, unknown>;
  const severity = normalizeSeverity(item.severity);
  const title =
    typeof item.title === 'string'
      ? truncateText(compactWhitespace(item.title), MAX_TITLE_CHARS)
      : '';
  const summary =
    typeof item.summary === 'string'
      ? truncateText(compactWhitespace(item.summary), MAX_SUMMARY_CHARS)
      : '';

  if (!severity || !title || !summary) return null;

  const filePath =
    typeof item.filePath === 'string'
      ? item.filePath.trim()
      : typeof item.file === 'string'
        ? item.file.trim()
        : undefined;

  const line =
    typeof item.line === 'number' && Number.isInteger(item.line) && item.line > 0
      ? item.line
      : undefined;

  const confidence =
    typeof item.confidence === 'number' && Number.isFinite(item.confidence)
      ? Math.max(0, Math.min(1, item.confidence))
      : undefined;

  const suggestion =
    typeof item.suggestion === 'string' && item.suggestion.trim()
      ? truncateText(item.suggestion.trim(), MAX_SUGGESTION_CHARS)
      : undefined;

  return {
    severity,
    title,
    summary,
    suggestion,
    filePath: filePath || undefined,
    line,
    confidence,
  };
}

/** Build the review prompt sent to the LLM */
export function buildPrompt(
  request: GatewayReviewRequest,
  truncated: boolean
): string {
  const fileList = request.files
    .map((file) => `- ${file.path} (${file.status ?? 'modified'})`)
    .join('\n');
  const isAgent = request.context?.agent?.isAgentAuthored === true;

  const jsonShape = isAgent
    ? '{"findings":[{"severity":"low|medium|high|critical","title":"...","summary":"...","suggestion":"...","filePath":"...","line":123,"confidence":0.0}]}'
    : '{"findings":[{"severity":"low|medium|high|critical","title":"...","summary":"...","filePath":"...","line":123,"confidence":0.0}]}';

  const rules = [
    '- Findings must be concrete and evidence-based.',
    '- Report only issues directly grounded in changed lines from this diff.',
    '- If you cannot anchor a finding to a specific changed line, omit it.',
    '- Do not suggest cosmetic renames or data-model renames/migrations unless diff shows a concrete bug.',
    '- Use higher severity only for significant risk.',
    '- Use filePath and line when possible.',
    '- Keep title concise (max 12 words).',
    '- Keep summary concise (max 28 words).',
    '- Avoid filler text, disclaimers, and repetition.',
    '- confidence must be between 0 and 1.',
  ];

  if (isAgent) {
    rules.push(
      '- This PR was generated by an AI coding agent. Apply agent-specific review rules:',
      '- Flag hallucinated APIs, packages, or imports that do not exist in the project.',
      '- Flag over-engineering: unnecessary abstractions, excessive configurability, premature generalization.',
      '- Flag copy-paste artifacts: duplicate code blocks, stale imports, dead code left by the agent.',
      '- Flag hardcoded secrets, disabled safety checks, or skipped validations.',
      '- For each finding, provide a "suggestion" field with the corrected code snippet.'
    );
  }

  if (truncated) {
    rules.push('- Note: diff content was truncated for token safety.');
  }

  return [
    'Review this pull request diff and return ONLY JSON with this shape:',
    jsonShape,
    'Rules:',
    ...rules,
    '',
    `Review tone: ${request.context?.reviewTone ?? 'balanced'}`,
    `Repository: ${request.context?.repoFullName ?? 'unknown'}`,
    `PR Number: ${request.context?.prNumber ?? 'unknown'}`,
    '',
    'Changed files:',
    fileList || '- none',
    '',
    'Diff:',
    request.diff,
  ]
    .filter(Boolean)
    .join('\n');
}

/** Parse raw LLM JSON response into validated findings */
export function parseReviewResponse(messageContent: string): ReviewFinding[] {
  let inner: unknown;
  try {
    inner = JSON.parse(messageContent);
  } catch {
    throw new Error('Review response content was not valid JSON.');
  }

  const rawFindings =
    inner &&
    typeof inner === 'object' &&
    Array.isArray((inner as { findings?: unknown }).findings)
      ? (inner as { findings: unknown[] }).findings
      : [];

  return rawFindings
    .map(coerceFinding)
    .filter((finding): finding is ReviewFinding => finding !== null);
}
